/*

        {
            img: '/01/01.png',
            txt: '#000000',
            bg: '#f4f4f4',
            web: false,
            shadow: true,
        },
*/
export const Project = {

    global: {
        date: '2021.05.28',
        proposer: 'Timeoff',
        title: 'Parade Artist Visual Identity Plan',
        transition: 'normal',
        txt: '#000000',
        bg: '#f4f4f4',
    },

    items: [
        {
            img: '/base/cover.jpg',
            bg: '#f4f4f4',
            shadow: false,
            web: false,
            scroll: false,
            label: 'Title',
        },
        {
            img: '/graphic/logo1.png',
            bg: '#f4f4f4',
            shadow: false,
            web: false,
            scroll: false,
            label: 'Logo',
        },
//         {
//             img: '/graphic/logo2.jpg',
//             bg: '#f4f4f4',
//             shadow: false,
//             web: false,
//             scroll: false,
//             label: 'Logo',
//         },
        {
            img: '/graphic/type1.jpg',
            bg: '#f4f4f4',
            shadow: false,
            web: false,
            scroll: false,
            label: 'Typography｜Roman',
        },
        {
            img: '/graphic/type2.jpg',
            bg: '#f4f4f4',
            shadow: false,
            web: false,
            scroll: false,
            label: 'Typography｜Japanese',
        },
        {
            img: '/graphic/type3.jpg',
            bg: '#f4f4f4',
            shadow: false,
            web: false,
            scroll: false,
            label: 'Typography｜Phonogram 1',
        },
        {
            img: '/web/home.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Home',
        },
        {
            img: '/web/home-memo.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Home｜Memo',
        },
        {
            img: '/web/listen.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: false,
            label: 'Web｜Listen Popup',
        },
        {
            img: '/web/home-2.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Home｜トクヒサレナ',
        },
        {
            img: '/web/home-4.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Home｜男性',
        },
        
        
        {
            img: '/web/mb-home-1.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: false,
            scroll: false,
            label: 'Web｜Mobile｜Home',
        },
        
        {
            img: '/web/live.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Live',
        },
        {
            img: '/web/note-list.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Note｜Index',
        },
        {
            img: '/web/note.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Note｜Article',
        },
        {
            img: '/web/release.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Music｜Release',
        },
        {
            img: '/web/video.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Music｜Video',
        },
        {
            img: '/web/fhilosophy.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Fhilosophy',
        },
        {
            img: '/web/artist-list.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Artist｜Index',
        },
        
        
        
        
        
        {
            img: '/web/mei-home.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: false,
            label: 'Web｜Mei｜Home',
        },
        {
            img: '/web/mei-live1.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Mei｜Live',
        },
        {
            img: '/web/mei-live2.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Mei｜Live',
        },
        {
            img: '/web/mei-release.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Mei｜Live',
        },
        {
            img: '/web/mei-movie.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: true,
            label: 'Web｜Mei｜Live',
        },
        {
            img: '/web/mei-home-mb.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: false,
            scroll: false,
            label: 'Web｜Mei｜Mobile',
        },
        
        
        
        {
            img: '/web/nidan-home.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: false,
            label: 'Web｜二段優希',
        },
        
        {
            img: '/web/rena-home1.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: false,
            label: 'Web｜トクヒサレナ A',
        },
        {
            img: '/web/rena-home2.jpg',
            bg: '#f2f2f2',
            shadow: true,
            web: true,
            scroll: false,
            label: 'Web｜トクヒサレナ B',
        },
        {
            img: '/graphic/image1.jpg',
            bg: '#fcfcfc',
            shadow: false,
            web: false,
            scroll: false,
            label: 'Brand Image',
        },
        {
            img: '/graphic/card1.jpg',
            bg: '#e7e7e7',
            shadow: false,
            web: false,
            scroll: false,
            label: 'Card',
        },
        {
            img: '/graphic/envelope2.jpg',
            bg: '#f5f4f3',
            shadow: false,
            web: false,
            scroll: false,
            label: 'Envelope',
        },
        {
            img: '/graphic/envelope4.jpg',
            bg: '#ededec',
            shadow: false,
            web: false,
            scroll: false,
            label: 'Cards & Envelopes',
        },
    ],

};

